### ISSUE TITLE
Huge reverb issue with this demo

### ISSUE THREAD

**Issue by anthodb** [daily-demos/custom-video-daily-react-hooks#18]
Hello Dear Daily developers,

Just by cloning the repo, changing api key and "npm run start", we have huge audio reverb issue. 
I mean, echo issue.. Is this something normal? Do you have any solution for this?

Tested with multiple users, single user alone in the room, on different computers. 
Using Chrome browser.

**Comment by lazeratops** [comment]
Thanks for reporting this! I had an initial look and have a suspicion of what the issue may be. Will take a closer look to confirm and provide an update tomorrow.

**Comment by anthodb** [comment]
Wow! What a fast reply ;) Thanks!
To help you in your search, we don't seem to have the issue with this demo here : 
https://github.com/daily-demos/call-object-react

Hope this helps!

**Comment by lazeratops** [comment]
Hello again! This should be fixed now. The echoing was related to us adding an audio element for the local user, which isn't needed.

**Comment by anthodb** [comment]
Great! Working perfectly now ;) Thanks for the fast modifications!
