### ISSUE TITLE
Multi Camera Setup

### ISSUE THREAD

**Issue by dlange82** [daily-demos/custom-video-daily-react-hooks#23]
Hello Daily Developers,

we are in need of a multi camera setup. Like one person wants to share 3 webcams.
It seems like the useDevices() hook cannot solve this problem. By loading multiple components with this hook, the only thing that happens is that one device is switched.

**Comment by nienkedekker** [comment]
Hi @dlange82 - apologies for the late response. We don't have a convenient hook or method for sharing multiple video streams, unfortunately. The best thing to do would be to have that person join a call multiple times from a different browser tab (so a new `sessionId` is generated for that user).

I'm interested in your use case, though! Would you mind sharing why you need a multi camera setup? :)
