### ISSUE TITLE
Could not create rtc connection

### ISSUE THREAD

**Issue by webface** [daily-demos/custom-video-daily-react-hooks#27]
Im trying to run the example on a mac but everytime i try to join a room i get the following error in the console.

```
​ error: could not create rtc connection: SyntaxError: Failed to construct 'RTCPeerConnection': 'stun:global.stun.twilio.com:3478?transport=udp' is not a valid stun or turn URL. f31219b0-1686-408f-a12d-9f7009f45fe3
value @ unknown
​ Meeting ended in error: Error during call.
value @ unknown
DevTools failed to load source map: Could not load content for http://localhost:3000/call-machine-object-bundle.js.map?2f2271: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
​ peer-to-peer offer creation timed out f31219b0-1686-408f-a12d-9f7009f45fe3
value @ unknown
value @ unknown
eval @ unknown
onTimeout @ unknown
localhost/:1 Unchecked runtime.lastError: The message port closed before a response was received.
```

**Comment by lazeratops** [comment]
Hey @webface, thanks for reporting this! I just tried to repro this on Monterey 12.6 in Firefox, Chrome, and Safari with no luck. Would you mind sending through the exact OS version and browser you're using? And if you've made any changes locally to the repo and deps please let me know, then I can do a more specific test.

**Comment by webface** [comment]
Node Version 14.9.0
Chrome Version: 110.0.5
Firefox: 108.8.2
Repro: [(https://github.com/webface/daily_test)]

**Comment by lazeratops** [comment]
Hey @webface. Thanks again for the issue report. We are aware of the cause and will deploy a fix soon - definitely before the 110 release on February 1.

**Comment by webface** [comment]
@lazeratops has this been fixed?

**Comment by lazeratops** [comment]
@webface Yes, this should now be fixed. Please let me know if you're still encountering the problem in your testing.
