### ISSUE TITLE
How to inject audio

### ISSUE THREAD

**Issue by Harsh4999** [daily-demos/custom-video-daily-react-hooks#31]
how to inject audio like if I want to automate joining of a participant and from that participant I want to play an audio in the stream then how is it possible

**Comment by lazeratops** [comment]
Hi, @Harsh4999! 

Thanks for reaching out. I recommend looking into the [`startCustomTrack()`](https://docs.daily.co/reference/daily-js/instance-methods/start-custom-track#main) call object instance method for this. 

Rough example to get you started by one of our React engineers:

```
import {
  useDaily,
} from '@daily-co/daily-react';

export const ReactComponent = () => {
  const daily = useDaily();
  const trackName = await daily.startCustomTrack({
    track: yourCustomTrack,
  });

  return (
    //...
  );
}
```

Hope that helps!
